import React from "react";
import TextField from "@mui/material/TextField";
import Stack from "@mui/material/Stack";
import Autocomplete from "@mui/material/Autocomplete";

export default function ExerciseName(props) {
  const { value, onChange } = props;

  const handleChange = (event, newValue) => {
    const selectedValue = newValue ? newValue : "";
    onChange({ target: { value: selectedValue } });
  };

  return (
    <Stack spacing={2} sx={{ width: 300 }}>
      <Autocomplete
        onChange={handleChange}
        value={value}
        id="free-solo-2-demo"
        options={exercises.map((option) => option.name)}
        renderInput={(params) => (
          <TextField
            {...params}
            label="Exercise"
            InputProps={{
              ...params.InputProps,
              type: "search",
            }}
          />
        )}
        freeSolo
        blurOnSelect
        selectOnFocus
        handleHomeEndKeys
        renderOption={(props, option) => <li {...props}>{option}</li>}
        inputValue={value}
        onInputChange={(event, newInputValue) => {
          handleChange(event, newInputValue);
        }}
      />
    </Stack>
  );
}

const exercises = [
  { name: "Curl" },
  { name: "Squat" },
  { name: "Bench" },
  { name: "Deadlift" },
  { name: "Pull-up" },
  { name: "Push-up" },
  { name: "Dumbbell Row" },
  { name: "Military Press" },
  { name: "Barbell Row" },
  { name: "Dumbbell Press" },
  { name: "Lateral Raise" },
  { name: "Chest Fly" },
  { name: "Tricep Pushdown" },
  { name: "Tricep Extension" },
  { name: "Barbell Curl" },
  { name: "Dumbbell Curl" },
  { name: "Leg Press" },
  { name: "Leg Extension" },
  { name: "Leg Curl" },
  { name: "Calf Raise" },
  { name: "Romanian Deadlift" },
  { name: "Hamstring Curl" },
  { name: "Incline Bench Press" },
  { name: "Decline Bench Press" },
  { name: "Dips" },
  { name: "Close Grip Bench Press" },
  { name: "Pulldown" },
  { name: "Seated Cable Row" },
  { name: "Arnold Press" },
  { name: "Front Raise" },
  { name: "Reverse Fly" },
  { name: "Hammer Curl" },
  { name: "Preacher Curl" },
  { name: "Skull Crusher" },
  { name: "Rear Delt Fly" },
  { name: "Good Morning" },
  { name: "Reverse Curl" },
  { name: "Crunch" },
  { name: "Russian Twist" },
  { name: "Plank" },
  { name: "Side Plank" },
  { name: "Hanging Leg Raise" },
  { name: "Lunge" },
  { name: "Step-Up" },
  { name: "Glute Bridge" },
  { name: "Hyperextension" },
  { name: "Cable Crunch" },
  { name: "Ab Wheel Rollout" },
  { name: "Wrist Curl" },
  { name: "Wrist Extension" },
  { name: "Hack Squat" },
  { name: "Front Squat" },
  { name: "Sumo Deadlift" },
  { name: "Bent-Over Row" },
  { name: "Seated Dumbbell Press" },
  { name: "Upright Row" },
  { name: "Pec Deck Fly" },
  { name: "Diamond Push-up" },
  { name: "EZ-Bar Curl" },
  { name: "Hammer Strength Row" },
  { name: "Side Lateral Raise" },
  { name: "Cable Bicep Curl" },
  { name: "Seated Leg Curl" },
  { name: "Adductor Machine" },
  { name: "Abductor Machine" },
  { name: "Stiff-Leg Deadlift" },
  { name: "Dumbbell Pullover" },
  { name: "Reverse-Grip Pulldown" },
  { name: "Seated Cable Curl" },
  { name: "Cable Tricep Pushdown" },
  { name: "Standing Calf Raise" },
  { name: "Hamstring Press" },
  { name: "Wide-Grip Pulldown" },
  { name: "Smith Machine Squat" },
  { name: "Smith Machine Bench Press" },
  { name: "Incline Dumbbell Press" },
  { name: "Decline Dumbbell Press" },
  { name: "Tricep Dip Machine" },
  { name: "Incline Dumbbell Curl" },
  { name: "Cable Crossover" },
  { name: "Lying Leg Curl" },
  { name: "Seated Leg Extension" },
  { name: "Single-Leg Press" },
  { name: "Single-Arm Dumbbell Row" },
  { name: "Machine Shoulder Press" },
  { name: "Dumbbell Fly" },
  { name: "Tricep Kickback" },
  { name: "Zottman Curl" },
  { name: "Cable Rear Delt Fly" },
  { name: "Donkey Calf Raise" },
  { name: "Seated Calf Raise" },
  { name: "Smith Machine Reverse Lunge" },
  { name: "Single-Leg Glute Bridge" },
  { name: "Hyperextension Machine" },
  { name: "Standing Cable Crunch" },
  { name: "Hanging Knee Raise" },
  { name: "Seated Leg Press" },
  { name: "Seated Hamstring Curl" },
  { name: "Seated Calf Machine" },
  { name: "Roman Chair Leg Raise" },
  { name: "Front Squat Smith Machine" },
  { name: "Behind-The-Back Wrist Curl" },
  { name: "Reverse Wrist Curl" },
  { name: "Hammer Curl Rope" },
  { name: "Machine Bicep Curl" },
  { name: "Standing Dumbbell Reverse Fly" },
  { name: "Plate Crunch" },
  { name: "Bulgarian Split Squat" },
  { name: "Stiff-Leg Barbell Deadlift" },
  { name: "Hack Squat Machine" },
  { name: "Bent-Over Dumbbell Row" },
  { name: "Machine Shoulder Press" },
  { name: "Seated Dumbbell Fly" },
  { name: "Rope Pushdown" },
  { name: "Standing Dumbbell Curl" },
  { name: "Leg Press Machine" },
  { name: "Leg Extension Machine" },
  { name: "Lying Leg Curl Machine" },
  { name: "Seated Calf Raise Machine" },
  { name: "Smith Machine Romanian Deadlift" },
  { name: "One-Arm Dumbbell Row" },
  { name: "Hammer Strength Shoulder Press" },
  { name: "Incline Cable Fly" },
  { name: "Overhead Cable Tricep Extension" },
  { name: "Machine Preacher Curl" },
  { name: "Smith Machine Shrug" },
  { name: "Seated Leg Press Machine" },
  { name: "Dumbbell Lunges" },
  { name: "Single-Leg Press Machine" },
  { name: "T-Bar Row" },
  { name: "Dumbbell Shoulder Press" },
  { name: "Lying Cable Fly" },
  { name: "Machine Tricep Extension" },
  { name: "Hammer Strength Chest Press" },
  { name: "Cable Hammer Curl" },
  { name: "Seated Dumbbell Curl" },
  { name: "Cable Front Raise" },
  { name: "Machine Rear Delt Fly" },
  { name: "Smith Machine Calf Raise" },
  { name: "Smith Machine Lunge" },
  { name: "Seated Calf Raise Machine" },
  { name: "Plate Twist" },
  { name: "Sumo Squat" },
  { name: "Leg Curl Machine" },
  { name: "Hip Thrust" },
  { name: "Cable Woodchopper" },
  { name: "Cable Crunch Machine" },
  { name: "Decline Sit-Up" },
  { name: "Seated Leg Extension Machine" },
  { name: "Standing Hamstring Curl Machine" },
  { name: "Leg Adductor Machine" },
  { name: "Leg Abductor Machine" },
  { name: "Machine Bicep Curl" },
  { name: "Rope Hammer Curl" },
  { name: "Smith Machine Behind-The-Back Shrug" },
  { name: "Barbell Reverse Wrist Curl" },
  { name: "Seated Alternating Dumbbell Curl" },
  { name: "Cable Rear Delt Fly Machine" },
  { name: "Cable Rope Overhead Tricep Extension" },
  { name: "Single-Arm Hammer Strength Row" },
  { name: "Cable Face Pull" },
  { name: "Machine Hip Adductor" },
  { name: "Machine Hip Abductor" },
  { name: "Machine Preacher Curl" },
  { name: "Machine Lateral Raise" },
  { name: "Dumbbell Upright Row" },
  { name: "Machine Lying Leg Curl" },
  { name: "Cable Seated Row" },
  { name: "Hammer Strength Chest Press" },
  { name: "Cable Lateral Raise" },
  { name: "Cable Tricep Pushdown Machine" },
  { name: "Machine Incline Press" },
  { name: "Hammer Strength Preacher Curl" },
  { name: "Cable Shrugs" },
  { name: "Smith Machine Close-Grip Bench Press" },
  { name: "Smith Machine Bent-Over Row" },
  { name: "Machine Shoulder Shrug" },
  { name: "Smith Machine Overhead Press" },
  { name: "Machine Fly" },
  { name: "Machine Tricep Dip" },
  { name: "Cable Hammer Curl Machine" },
  { name: "Dumbbell Shoulder Fly" },
  { name: "Machine Calf Raise" },
  { name: "Machine Leg Press" },
  { name: "Cable Leg Extension" },
  { name: "Cable Leg Curl" },
  { name: "Cable Calf Raise" },
  { name: "Smith Machine Romanian Deadlift" },
  { name: "Machine Lat Pulldown" },
  { name: "Smith Machine Arnold Press" },
  { name: "Smith Machine Front Raise" },
  { name: "Machine Rear Delt Fly" },
  { name: "Smith Machine Good Morning" },
  { name: "Smith Machine Reverse Curl" },
  { name: "Machine Crunch" },
  { name: "Machine Russian Twist" },
  { name: "Machine Plank" },
  { name: "Machine Side Plank" },
  { name: "Machine Hanging Leg Raise" },
  { name: "Machine Lunge" },
  { name: "Machine Step-Up" },
  { name: "Machine Glute Bridge" },
  { name: "Machine Hyperextension" },
  { name: "Machine Cable Crunch" },
  { name: "Machine Ab Wheel Rollout" },
  { name: "Machine Wrist Curl" },
  { name: "Machine Wrist Extension" },
];

// Total: 200 exercises
